#NOT AN ACTUAL PLAYBOOK
#just a reference for introducing Ansible to new Linux Team members on CSUN CCDC Team

#Installation
sudo apt-get install ansible
sudo yum install ansible

#Host file set up
- name: install and start apache  #### Human understandable naming convention
  hosts: web                      #### Host selector
    become: yes                   #### Privilege escalation to root
    vars:                         #### Variables used by the playbook
      http_port: 80
      vhost: Ansible-Test-VM
tasks:                            #### Tasks performed by the playbook
- name: httpd package is present
  yum:
    name: httpd
    state: latest
- name: latest index.html file is present
  copy:
    src: files/index.html
    dest: /var/www/html/
    
tasks:                            #### Playing around with using vars
  - name: create a virtual host file for {{ vhost }}
    template:
      src: somefile.j2
      dest: /etc/httpd/conf.d/{{ vhost }}

tasks:                            #### How to use "command" option
  - name: enable selinux
    command: /sbin/setenforce 1
    
tasks:                            #### How to use "shell" option
  - name: run this command and ignore the result
    shell: /usr/bin/somecommand
    ignore_errors: True

# Handlers
handlers:
    - name: restart memcached
      service:
        name: memcached
        state: restarted
      listen: "restart web services"
    - name: restart apache
      service:
        name: apache
        state: restarted
      listen: "restart web services"

tasks:
- name: write the apache config file
    template:
      src: /media/user/apache-config
      dest: /etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: now also make sure memcached is restarted
    notify: "restart web services"

#Loops
- yum:
name: "{{ item }}"
state: latest
with_items:
- httpd
- mariadb
- php

#Conditionals
- yum:
name: httpd
state: latest
when: ansible_os_family == "RedHat"

#Adding user
- name: Add a user
  hosts: all
  tasks:
    - name: Add User
      user:
        name: admin
        comment: admin
        uid: 10420
        group: admin
        shell: /bin/zsh
        password: "admin"
        state: present
        
#Remove user
- name: Remove user
  hosts: localhost
  tasks:
    - name: Remove User
    user:
      name: admin
      state: absent
      remove: yes
      
# Install updates
- hosts: all
  sudo: yes
  tasks:
    - name: .rpm upgrade
      yum: >
        update_cache=yes
        name=*
        state=latest
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'
        
    - name: .deb upgrade
      apt: >
        update_cache=yes
        cache_valid_time=1200
        state=latest
        upgrade=dist
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'
        
# Install updates ONLY to CentOS with AdHoc
ansible centos -m yum -a "name=* state=latest" -b

# Reboot all machines
ansible all -a "reboot" -s

#If you want to run the same command/variable/role
allow_duplicates: true

#Do you not care about errors?
ignore_errors: True

#Check hosts affected
ansible-playbook playbook.yml --list-hosts

#Run playbook
ansible-playbook playbook.yml

#https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html
#need to actually read up on using the roles:
#https://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_roles.html
#apparently by default the roles are stored in /etc/ansible/roles
#another page for playbook intro
#https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html
